Merge some modifications made in private repo
farao-community/gridcapa-rao-runner pull request #16
Opened 2021-12-20 14:25 UTC by baptsegu

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [X] The commit message follows our guidelines
- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*

Handle targetEndInstant of RAO.
Add information on instant at beginning and end of RAO in request and response.
Add some small changes made in the private repo.

**Does this PR introduce a breaking change?** *(What changes might users need to make in their application due to this PR?)*

yes, new fields in RaoRequest and RaoResponse

2021-12-27 11:25 UTC, TheMaskedTurtle requested changes

2021-12-27 11:25 UTC, TheMaskedTurtle commented on rao-runner-app/src/main/java/com/farao_community/farao/rao_runner/app/RaoRunnerListener.java
> +            RaoRunnerException wrappingException = new RaoRunnerException("Unknown exception", e);
I think it is good to keep the message you can see the failure reason more clearly

2021-12-27 11:25 UTC, TheMaskedTurtle commented on rao-runner-app/pom.xml
> +        </dependency>
Why do you need that ?

2021-12-27 11:25 UTC, TheMaskedTurtle commented on rao-runner-api/pom.xml
> +        </dependency>
Alphabetical order we class from group id first

2021-12-27 11:25 UTC, TheMaskedTurtle commented on pom.xml
> +            </dependency>
Same, is that useful ?

2021-12-27 11:25 UTC, TheMaskedTurtle commented on docker-compose.yml
> +    image: rabbitmq:management-alpine
We can match images on what we use in gridcapa-deployment : rabbitmq:management

2021-12-27 11:25 UTC, TheMaskedTurtle commented on docker-compose.yml
> +    image: minio/minio:latest
We can match images on what we use in gridcapa-deployment : bitnami/minio:2021.6.17

2021-12-27 11:25 UTC, TheMaskedTurtle commented on rao-runner-api/src/main/java/com/farao_community/farao/rao_runner/api/JsonApiConverter.java
> +
Can remove empty line

2021-12-28 11:26 UTC, TheMaskedTurtle requested changes

2021-12-28 11:26 UTC, TheMaskedTurtle commented on pom.xml
> +            </dependency>
As mentioned in the farao-parent MR this shouldn't be added here as well

2021-12-28 11:26 UTC, TheMaskedTurtle commented on rao-runner-app/pom.xml
> +        </dependency>
To be removed

2022-01-03 09:36 UTC, baptsegu commented on rao-runner-app/src/main/resources/application.yml
> +      expiration: 600000 # (10x60s), time for applications to read the response
it's the expiration time of the RaoResponse, not the RaoRequest.

RaoResponses will stay 10 minutes in their dedicated queue before being deleted. So 10 minutes is the max amount of time between the end of the RAO, and the moment when applications actually record that the RAO is finished.

We can maybe increase it a bit, but 2 hours seem long. I think that we reduce this value, to avoid some strange behaviours when we restart our RAO-integration application after its crash.

2022-01-03 09:54 UTC, baptsegu commented on rao-runner-app/src/main/resources/logback.xml
> +    <logger name="org.springframework" level="OFF"/>
ok, i change it

2022-01-03 09:54 UTC, baptsegu commented on rao-runner-app/src/main/java/com/farao_community/farao/rao_runner/app/RaoRunnerListener.java
> +            RaoRunnerException wrappingException = new RaoRunnerException("Unknown exception", e);
indeed

2022-01-03 09:56 UTC, baptsegu commented on docker-compose.yml
> +    image: rabbitmq:management-alpine
ok

2022-01-03 09:56 UTC, baptsegu commented on docker-compose.yml
> +    image: minio/minio:latest
ok

2022-01-03 09:57 UTC, baptsegu commented on rao-runner-api/pom.xml
> +        </dependency>
done

2022-01-03 09:58 UTC, baptsegu commented on rao-runner-api/src/main/java/com/farao_community/farao/rao_runner/api/JsonApiConverter.java
> +
ok

2022-01-19 08:13 UTC, TheMaskedTurtle commented on rao-runner-app/src/main/resources/application.yml
> +      expiration: 600000 # (10x60s), time for applications to read the response
true !

2022-01-19 09:46 UTC, TheMaskedTurtle approved these changes

2022-01-19 09:47 UTC, TheMaskedTurtle requested changes

2022-01-19 09:47 UTC, TheMaskedTurtle commented on rao-runner-app/src/main/java/com/farao_community/farao/rao_runner/app/RaoRunnerListener.java
> +            System.gc();
Why do you call garbage collector here ?

2022-01-19 09:56 UTC, baptsegu commented on rao-runner-app/src/main/java/com/farao_community/farao/rao_runner/app/RaoRunnerListener.java
> +            System.gc();
to free the RAM.

Othewise, the JVM of the rao-runner pod do not release the RAM at the end of the RAO run:

- It will be able to release it when needed for this pod, that is to say when a new RAO is run with this pod. 
- But, it will not see that it should release it if there is RAM pressure on the node coming from the other pods

2022-01-19 09:57 UTC, TheMaskedTurtle commented on rao-runner-app/src/main/java/com/farao_community/farao/rao_runner/app/RaoRunnerListener.java
> +            System.gc();
I see !

2022-01-19 10:12 UTC, TheMaskedTurtle approved these changes

2022-01-19 10:13 UTC, merged